### ISSUE TITLE
Content assist does not work 

### ISSUE THREAD

**Issue by Katka92** [redhat-developer/rh-che#1341]
**Issue problem:** 
When typing code, no offer is given. When writing corrupted code, no error/warning is given.
The issue is reproductible with those factories:
 - [x] Vert.x verticle - - fixed by adding `"org.eclipse.che.ls.java"` **pending QA verification** 
 - [x] Spring Rest Guide - fixed by adding `"org.eclipse.che.ls.java"` **pending QA verification** 
 - [x] Angular 2 - fixed by adding `"org.eclipse.che.ls.js-ts"` installer  **pending QA verification** 
 - [x] C++ - fixed by adding ` "org.eclipse.che.ls.clangd" installer  **pending QA verification** 
 - [ ] Java + Gradle - sepate issue https://github.com/redhat-developer/rh-che/issues/1344
 - [x] Java + Maven - fixed by adding `"org.eclipse.che.ls.java"` **pending QA verification**
 - [x] PHP - fixed by adding - "org.eclipse.che.exec","org.eclipse.che.ls.php"  **pending QA verification**
 - [x] Spring Boot -  fixed by adding `"org.eclipse.che.ls.java"` **pending QA verification**
 - [x] Vaadin -  fixed by adding `"org.eclipse.che.ls.java"` **pending QA verification**
 - [x] Wildfly - fixed by adding `"org.eclipse.che.ls.java"` **pending QA verification**

**Known issues:**
- [ ] [Java code assist is malfunctioning](https://github.com/eclipse/che/issues/13125)
- [ ] [CPP code assist is malfunctioning](https://github.com/eclipse/che/issues/13127)
- [ ] Java + Gradle - sepate issue https://github.com/redhat-developer/rh-che/issues/1344

Works in:
 - Spring
 - Node.js

**Reproduction Steps:**
Create factory by clicking on the link: https://che.openshift.io/f?id=factory3q5u5r3l7vim1u7g
Wait until the class ```HelloWorldVerticle``` is opened. Add ```config().``` to the ```12``` line. Content assist should offer you some choices, but nothing happens. It should also mark the next line with error/warning as the source code would not compile in this state. 

![Screenshot from 2019-04-02 08-38-55](https://user-images.githubusercontent.com/29278800/55381210-d1e1dc80-5522-11e9-93be-d1ecadc8060a.png)

Working example for comparison. Node.js factory used:

![Screenshot from 2019-04-02 08-43-32](https://user-images.githubusercontent.com/29278800/55381448-7d8b2c80-5523-11e9-8f19-136b3345f2b7.png)

**Runtime:**

runtime used:
   - [ ] minishift (include output of `minishift version`)
   - [x] OpenShift.io
   - [ ] Openshift Container Platform (include output of `oc version`)

**Comment by ibuziuk** [comment]
@tsmaeder any ideas why content assist got broken ?

```
2019-04-02 11:15:28,453[rviceProvider-1]  [ERROR] [oggingUncaughtExceptionHandler 32]   - Runtime exception caught in thread WsAgentWebSocketEndpointExecutorServiceProvider-1. Message: null
java.lang.NullPointerException: null
	at org.eclipse.che.api.core.jsonrpc.commons.RequestHandlerManager$OneToManyHandler.access$1100(RequestHandlerManager.java:374)
	at org.eclipse.che.api.core.jsonrpc.commons.RequestHandlerManager.handle(RequestHandlerManager.java:227)
	at org.eclipse.che.api.core.jsonrpc.commons.RequestDispatcher.dispatch(RequestDispatcher.java:52)
	at org.eclipse.che.api.core.jsonrpc.commons.JsonRpcMessageReceiver$ProcessRequestTask.run(JsonRpcMessageReceiver.java:112)
	at org.eclipse.che.api.core.jsonrpc.commons.reception.FunctionConfiguratorOneToMany.lambda$withFunction$0(FunctionConfiguratorOneToMany.java:77)
	at org.eclipse.che.api.core.jsonrpc.commons.RequestHandlerManager$OneToManyHandler.handle(RequestHandlerManager.java:389)
	at org.eclipse.che.plugin.java.languageserver.JavaLanguageServerExtensionService.getClasspathTree(JavaLanguageServerExtensionService.java:703)
	at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalRunnable.run(CopyThreadLocalRunnable.java:38)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.lang.Thread.run(Thread.java:748)
2019/04/02 11:15:28 Start new terminal.
2019-04-02 11:15:38,465[rviceProvider-0]  [ERROR] [oggingUncaughtExceptionHandler 32]   - Runtime exception caught in thread WsAgentWebSocketEndpointExecutorServiceProvider-0. Message: null
java.lang.NullPointerException: null
	at org.eclipse.che.api.core.jsonrpc.commons.RequestHandlerManager$OneToManyHandler.access$1100(RequestHandlerManager.java:374)
	at org.eclipse.che.api.core.jsonrpc.commons.RequestHandlerManager.handle(RequestHandlerManager.java:227)
	at org.eclipse.che.api.core.jsonrpc.commons.RequestDispatcher.dispatch(RequestDispatcher.java:52)
	at org.eclipse.che.api.core.jsonrpc.commons.JsonRpcMessageReceiver$ProcessRequestTask.run(JsonRpcMessageReceiver.java:112)
	at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalRunnable.run(CopyThreadLocalRunnable.java:38)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at org.eclipse.che.plugin.java.languageserver.JavaLanguageServerExtensionService.getClasspathTree(JavaLanguageServerExtensionService.java:703)
	at org.eclipse.che.api.core.jsonrpc.commons.RequestHandlerManager$OneToManyHandler.handle(RequestHandlerManager.java:389)
	at org.eclipse.che.api.core.jsonrpc.commons.reception.FunctionConfiguratorOneToMany.lambda$withFunction$0(FunctionConfiguratorOneToMany.java:77)
java.lang.NullPointerException: null
2019-04-02 11:15:39,408[rviceProvider-3]  [ERROR] [oggingUncaughtExceptionHandler 32]   - Runtime exception caught in thread WsAgentWebSocketEndpointExecutorServiceProvider-3. Message: null
	at org.eclipse.che.api.core.jsonrpc.commons.RequestHandlerManager$OneToOneHandler.handle(RequestHandlerManager.java:351)
	at org.eclipse.che.api.core.jsonrpc.commons.RequestHandlerManager$OneToOneHandler.access$1000(RequestHandlerManager.java:335)
	at org.eclipse.che.api.core.jsonrpc.commons.RequestHandlerManager.handle(RequestHandlerManager.java:224)
	at org.eclipse.che.api.core.jsonrpc.commons.RequestDispatcher.dispatch(RequestDispatcher.java:52)
	at org.eclipse.che.plugin.java.testing.AbstractJavaTestRunner.detectTests(AbstractJavaTestRunner.java:52)
	at org.eclipse.che.api.core.jsonrpc.commons.JsonRpcMessageReceiver$ProcessRequestTask.run(JsonRpcMessageReceiver.java:112)
	at org.eclipse.che.plugin.java.languageserver.JavaLanguageServerExtensionService.detectTest(JavaLanguageServerExtensionService.java:405)
	at org.eclipse.che.api.testing.server.TestingRPCService.handleTestDetection(TestingRPCService.java:102)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.lang.Thread.run(Thread.java:748)
	at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalRunnable.run(CopyThreadLocalRunnable.java:38)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
2019-04-02 11:15:50,465[rviceProvider-4]  [ERROR] [oggingUncaughtExceptionHandler 32]   - Runtime exception caught in thread WsAgentWebSocketEndpointExecutorServiceProvider-4. Message: null
java.lang.NullPointerException: null
	at org.eclipse.che.api.testing.server.TestingRPCService.handleTestDetection(TestingRPCService.java:102)
	at org.eclipse.che.api.core.jsonrpc.commons.RequestHandlerManager$OneToOneHandler.handle(RequestHandlerManager.java:351)
	at org.eclipse.che.api.core.jsonrpc.commons.RequestHandlerManager$OneToOneHandler.access$1000(RequestHandlerManager.java:335)
	at org.eclipse.che.api.core.jsonrpc.commons.RequestDispatcher.dispatch(RequestDispatcher.java:52)
	at org.eclipse.che.api.core.jsonrpc.commons.JsonRpcMessageReceiver$ProcessRequestTask.run(JsonRpcMessageReceiver.java:112)
	at org.eclipse.che.plugin.java.languageserver.JavaLanguageServerExtensionService.detectTest(JavaLanguageServerExtensionService.java:405)
	at org.eclipse.che.plugin.java.testing.AbstractJavaTestRunner.detectTests(AbstractJavaTestRunner.java:52)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalRunnable.run(CopyThreadLocalRunnable.java:38)
	at org.eclipse.che.api.core.jsonrpc.commons.RequestHandlerManager.handle(RequestHandlerManager.java:224)
	at java.lang.Thread.run(Thread.java:748)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)

```

**Comment by tsmaeder** [comment]
This is Che 6?

**Comment by tsmaeder** [comment]
The NPE's are irrelevant, because they would only affect the java content assist, not any others. It can be an indication that the Java language server is not running when it is needed. Together with the fact that no errors appear, I would think that the language servers are not started properly. As to why this would have started happening, I have no idea, the langugages team hasn't done any che related work in quite some time.

**Comment by ibuziuk** [comment]
this is che 7 beta 2 cc: @l0rd @slemeur

**Comment by tsmaeder** [comment]
But it is a GWT workspace, right?

**Comment by ibuziuk** [comment]
> But it is a GWT workspace, right?
correct

**Comment by ibuziuk** [comment]
@Katka92 @tdancs issue is pending QA verifications. Details are in the updated description

**Comment by tsmaeder** [comment]
@ibuziuk so this is a misconfiguration of the workspace (installers missing)?

**Comment by ibuziuk** [comment]
@tsmaeder yup, but not for gradle case which is still not usable in GWT for me - https://github.com/redhat-developer/rh-che/issues/1344

**Comment by ScrewTSW** [comment]
I've finished testing according to https://github.com/redhat-developer/rh-che/issues/1341
Changes have been marked by `EDIT:`
https://docs.google.com/document/d/1aRf2DdZ_LCWQDABdBc836y2oAT0DE3-iWFLJoprtGuQ/edit?usp=sharing

Issues for LSP bayesian have been created: https://github.com/eclipse/che/issues/13125 https://github.com/eclipse/che/issues/13127

**Comment by ibuziuk** [comment]
Closing, since all the follow up issues have been reported separately:

**Known issues:**
- [ ] [Java code assist is malfunctioning](https://github.com/eclipse/che/issues/13125)
- [ ] [CPP code assist is malfunctioning](https://github.com/eclipse/che/issues/13127)
- [ ] Java + Gradle - sepate issue https://github.com/redhat-developer/rh-che/issues/1344
