### ISSUE TITLE
Sprint 134

### ISSUE THREAD

**Issue by ibuziuk** [redhat-developer/rh-che#138]
## Working hours budget
https://docs.google.com/spreadsheets/d/1_YsNaGRHID0QNPdSOJYk6tmlBux1kZK_YN8eCCIpzmY/edit#gid=94829851

### Issues tied to objectives
- [ ] Rebase openshift-connector to master - https://github.com/redhat-developer/rh-che/issues/146 **estimation**:  125
- [ ] Workspace pod logs https://github.com/redhat-developer/rh-che/issues/145 - **estimation**: 20
- [ ] Workspace idling https://github.com/redhat-developer/rh-che/issues/144  - **estimation**: 15
- [x] Add a property to disable keycloak authentication in rh-che assembly https://github.com/redhat-developer/rh-che/issues/142 - **estimation**: 15
- [x] Fix workspace keycloak authentication https://github.com/redhat-developer/rh-che/issues/139 - **estimation**: 15
- [x] OpenShift branch Docker strategies to update before going to master branch https://github.com/redhat-developer/rh-che/issues/113 - **estimation**: 5
- [ ] Setting header Authorization: Internal allows bypassing keycloak on Che https://github.com/redhat-developer/rh-che/issues/137 - **estimation**: 15
- [x] 503s are back https://github.com/redhat-developer/rh-che/issues/115 - **estimation**: 10
- [x] 401s on Content assis https://github.com/redhat-developer/rh-che/issues/94 - **estimation**: 25
- [ ] Bug: Che doesn't show analytics error when opening it https://github.com/redhat-developer/rh-che/issues/101 - **estimation**: 10
- [x] .NET stacktrace support https://github.com/eclipse/che/issues/5489 - **estimation**: 25
- [ ] Enable multiple language servers to be registered for a single file	
 https://issues.jboss.org/browse/CHE-198 - **estimation**: 10
- [ ] Support for Executing LSP WorkspaceEdit  https://github.com/eclipse/che/issues/5485 - **estimation**: 25
- [ ] Inconsistencies between stacks https://github.com/redhat-developer/rh-che/issues/147 **estimation**: 15
- [ ] Add option to start workspaces on a different namespace https://github.com/redhat-developer/rh-che/issues/131 **estimation**: 20
- [ ] Inject user KC token in bayesian LS https://github.com/redhat-developer/rh-che/issues/141 **estimation**: 40

### Merge-ready PRs
- [ ] https://github.com/redhat-developer/rh-che/pull/196 

### Metrics

|  | Planned | Result |
| --- | --: | --: |
| **Budget** | 390 |  |
## Sprint Queries

**Enterprise Team**:
[`issues: all`](https://github.com/issues?utf8=%E2%9C%93&q=label%3Asprint%2Fcurrent-sprint+label%3Ateam%2Fenterprise+repo%3Aeclipse%2Fche+repo%3Acodenvy%2Fcodenvy+repo%3Acodenvy%2Fartik-enterprise+repo%3Acodenvy%2Fplanning+repo%3Acodenvy%2Fcustomer-saas), [`issues: open`](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aopen+label%3Asprint%2Fcurrent-sprint+label%3Ateam%2Fenterprise+repo%3Aeclipse%2Fche+repo%3Acodenvy%2Fcodenvy+repo%3Acodenvy%2Fartik-enterprise+repo%3Acodenvy%2Fplanning+repo%3Acodenvy%2Fcustomer-saas+), [`issues: closed`](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aclosed+label%3Asprint%2Fcurrent-sprint+label%3Ateam%2Fenterprise+repo%3Aeclipse%2Fche+repo%3Acodenvy%2Fcodenvy+repo%3Acodenvy%2Fartik-enterprise+repo%3Acodenvy%2Fplanning+repo%3Acodenvy%2Fcustomer-saas+), [`issues: no status`](https://github.com/issues?utf8=%E2%9C%93&q=label%3Asprint%2Fcurrent-sprint+label%3Ateam%2Fenterprise+-label%3Astatus%2Fanalyzing+-label%3Astatus%2Fblocked+-label%3Astatus%2Fcode-review+-label%3Astatus%2Fin-progress+-label%3Astatus%2Finfo-needed+-label%3Astatus%2Fin-progress+-label%3Astatus%2Fwork-in-progress+-label%3Astatus%2Fopen-for-dev+-label%3Astatus%2Fpending-merge+repo%3Aeclipse%2Fche+repo%3Acodenvy%2Fcodenvy+repo%3Acodenvy%2Fartik-enterprise+repo%3Acodenvy%2Fplanning+repo%3Acodenvy%2Fcustomer-saas+),[`issues: pre-dev`](https://github.com/issues?utf8=%E2%9C%93&q=label%3Asprint%2Fcurrent-sprint+label%3Ateam%2Fenterprise+-label%3Astatus%2Fopen-for-dev+-label%3Astatus%2Fin-progress+-label%3Astatus%2Fcode-review+-label%3Astatus%2Fpending-merge+-label%3Astatus%2Fblocked+-label%3Astatus%2Fwork-in-progress+-label%3Astatus%2Fmerge-ready+repo%3Aeclipse%2Fche+repo%3Acodenvy%2Fcodenvy+repo%3Acodenvy%2Fartik-enterprise+repo%3Acodenvy%2Fplanning+repo%3Acodenvy%2Fcustomer-saas+),[`issues: dev`](https://github.com/issues?utf8=%E2%9C%93&q=label%3Asprint%2Fcurrent-sprint+label%3Ateam%2Fenterprise+-label%3Astatus%2Finfo-needed+-label%3Astatus%2Fanalyzing+-label%3Astatus%2Fopen-for-dev+-label%3Astatus%2Fpending-merge+-label%3Astatus%2Fblocked+-label%3Astatus%2Fwork-in-progress+repo%3Aeclipse%2Fche+repo%3Acodenvy%2Fcodenvy+repo%3Acodenvy%2Fartik-enterprise+repo%3Acodenvy%2Fplanning+repo%3Acodenvy%2Fcustomer-saas+),[`issues: pending merge`](https://github.com/issues?utf8=%E2%9C%93&q=label%3Asprint%2Fcurrent-sprint+label%3Ateam%2Fenterprise+-label%3Astatus%2Finfo-needed+-label%3Astatus%2Fanalyzing+-label%3Astatus%2Fopen-for-dev+-label%3Astatus%2Fin-progress+-label%3Astatus%2Fcode-review+-label%3Astatus%2Fblocked+-label%3Astatus%2Fwork-in-progress+repo%3Aeclipse%2Fche+repo%3Acodenvy%2Fcodenvy+repo%3Acodenvy%2Fartik-enterprise+repo%3Acodenvy%2Fplanning+repo%3Acodenvy%2Fcustomer-saas+)

[`bugs: blocker`](https://github.com/issues?utf8=%E2%9C%93&q=label%3Asprint%2Fcurrent-sprint+label%3Ateam%2Fenterprise+label%3Akind%2Fbug+label%3Aseverity%2Fblocker+repo%3Aeclipse%2Fche+repo%3Acodenvy%2Fcodenvy+repo%3Acodenvy%2Fartik-enterprise+repo%3Acodenvy%2Fplanning+repo%3Acodenvy%2Fcustomer-saas+),[`issues: blocked`](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aopen+label%3Asprint%2Fcurrent-sprint+label%3Ateam%2Fenterprise+label%3Astatus%2Fblocked+repo%3Aeclipse%2Fche+repo%3Acodenvy%2Fcodenvy+repo%3Acodenvy%2Fartik-enterprise+repo%3Acodenvy%2Fplanning+repo%3Acodenvy%2Fcustomer-saas+)

[`PRs: all`](https://github.com/issues?utf8=%E2%9C%93&q=is%3Apr+label%3Asprint%2Fcurrent-sprint+label%3Ateam%2Fenterprise+repo%3Aeclipse%2Fche+repo%3Acodenvy%2Fcodenvy+repo%3Acodenvy%2Fartik-enterprise+repo%3Acodenvy%2Fplanning+repo%3Acodenvy%2Fcustomer-saas+), [`PRs: open`](https://github.com/issues?utf8=%E2%9C%93&q=is%3Apr+is%3Aopen+label%3Asprint%2Fcurrent-sprint+label%3Ateam%2Fenterprise+repo%3Aeclipse%2Fche+repo%3Acodenvy%2Fcodenvy+repo%3Acodenvy%2Fartik-enterprise+repo%3Acodenvy%2Fplanning+repo%3Acodenvy%2Fcustomer-saas+), [`PRs: closed`](https://github.com/issues?utf8=%E2%9C%93&q=is%3Apr+is%3Aclosed+label%3Asprint%2Fcurrent-sprint+label%3Ateam%2Fenterprise+repo%3Aeclipse%2Fche+repo%3Acodenvy%2Fcodenvy+repo%3Acodenvy%2Fartik-enterprise+repo%3Acodenvy%2Fplanning+repo%3Acodenvy%2Fcustomer-saas+)

**Comment by l0rd** [comment]
@ibuziuk now that sprint 134 has ended should we close this one?

**Comment by ibuziuk** [comment]
yes I think so
