### ISSUE TITLE
Rebasing openshift-connector to upstream che master

### ISSUE THREAD

**Issue by ibuziuk** [redhat-developer/rh-che#146]
see - https://issues.jboss.org/browse/CHE-229

Rebase openshift-connector to master - https://github.com/redhat-developer/rh-che/issues/146 **estimation**:  125
- [x] Fix openshift-connector-rebased branch https://github.com/redhat-developer/rh-che/issues/151 - **PR:** https://github.com/eclipse/che/pull/5052 - **estimation**: 5
- [x] Move bayesian recommendation token support to rh-che https://github.com/redhat-developer/rh-che/issues/152 [CHE-271](https://issues.jboss.org/browse/CHE-271)  - **estimation**: 15
- [x] Verify that on master branch Unit Tests are started in their own process now  (c.f. CHE-214) https://github.com/redhat-developer/rh-che/issues/153 - **PR:** https://github.com/eclipse/che/pull/5472 -  [CHE-273](https://issues.jboss.org/browse/CHE-273) - **estimation**: 10
- [x] Improve idling implementation https://github.com/redhat-developer/rh-che/issues/154 - **PR:** https://github.com/eclipse/che/pull/5512   - **estimation**: 5
- [ ] Remove the need for rhche Docker images https://github.com/redhat-developer/rh-che/issues/155 [CHE-275](https://issues.jboss.org/browse/CHE-275) - **estimation**: 15
- [x] Support Language Servers in pom.xml editor  https://github.com/eclipse/che/issues/5492  - **estimation**: 30
- [x] Update the CI to use rebased branch https://github.com/redhat-developer/rh-che/issues/156 [CHE-279](https://issues.jboss.org/browse/CHE-279)  - **estimation**: 10
- [x] cannot start workspace https://github.com/redhat-developer/rh-che/issues/157 [CHE-297](https://issues.jboss.org/browse/CHE-297)  - **estimation**: 15
- [x] Adapt new stacks.json to the new policy change https://github.com/redhat-developer/rh-che/issues/124 - **estimation**: 10
- [x] Fix startup of bayesian analytics language server https://github.com/redhat-developer/rh-che/issues/166

**Comment by sunix** [comment]
rebased PR: https://github.com/redhat-developer/rh-che/pull/117

**Comment by l0rd** [comment]
Everything fixed except #155 but that's not really related to rebasing openshift-connector branch so closing this epic
