### ISSUE TITLE
[E2E] Create test for default stacks

### ISSUE THREAD

**Issue by Katka92** [redhat-developer/rh-che#1567]
Create tests for other stacks. Add those tests to upstream. Upstream issues related to that will be linked to this issue.
Stacks to tests:
- [ ] NodeJS Angular Web Application
- [ ] Apache Camel based on Spring Boot
- [ ] .NET Core
- [ ] Go
- [ ] Java Gradle
- [x] Java Maven - tested on Rh-Che side
- [ ] Java with Spring Boot and MySQL
- [ ] Java Spring Boot
- [x] Java Vert.x
- [ ] NodeJS Express Web Application
- [ ] NodeJS MongoDB Web Application
- [ ] NodeJS React Web Application
- [ ] PHP Laravel with MySQL
- [ ] PHP with MySQL
- [ ] PHP Symfony
- [ ] PHP Simple
- [ ] Python
- [ ] Django

**Comment by Katka92** [comment]
Test for Java Vertx PR: https://github.com/redhat-developer/rh-che/pull/1619

**Comment by Katka92** [comment]
This type of issue/epic should be tracked upstream. Currently, we are opening a new issue for every devfile that we are covering. I'm closing this epic without opening duplicate in upstream as it doesn't seem needed.
