### ISSUE TITLE
Initial Setup of the `che-workspace-telemetry-woopra-backend`

### ISSUE THREAD

**Issue by davidfestal** [redhat-developer/rh-che#1714]
**Description:**

Include the https://github.com/davidfestal/che-workspace-telemetry-woopra-backend base repo as a RhChe component,
and setup the CI build that will produce the corresponding native docker image, and the right meta.yaml to expose it as a remote plugin outside of the main plugin registry.
And add this remote plugin in the list of mandatory plugin in the wsmaster RHCHE properties 

- [x] setup CI for building an image on quay.io https://github.com/redhat-developer/rh-che/issues/1779
- [x] figure out where the meta.yaml for a new telemetry plugin (local plugin in che-theia) will be located - https://github.com/redhat-developer/rh-che/issues/1749
- [x] provide a mechanism for enabling this local plugin by default on che-theai - https://github.com/redhat-developer/rh-che/issues/1750

**Comment by ibuziuk** [comment]
@davidfestal wdyt maybe we should create a separate repo with dedicated ci for  https://github.com/davidfestal/che-workspace-telemetry-woopra-backend  ? 
I'm not sure if merging it to rh-che is the best choice

**Comment by davidfestal** [comment]
I'm ok with both options. Just do as is more convenient for you.

**Comment by ibuziuk** [comment]
@davidfestal are there any benefits in using rh-che ? otherwise for sure we should have this in a separate repo

**Comment by ibuziuk** [comment]
The repo has been created - https://github.com/redhat-developer/che-workspace-telemetry-woopra-backend

**Comment by ibuziuk** [comment]
quay repo has been created https://quay.io/repository/openshiftio/che-workspace-telemetry-woopra-backend
I'm not sure if we will be able to get a push rights though. @tomgeorge will it be possible to provide a Dockerfile to the repo [1] as a temp solution and I will quickly setup centos CI for it?

[1] https://github.com/redhat-developer/che-workspace-telemetry-woopra-backend

**Comment by tomgeorge** [comment]
@ibuziuk @davidfestal  CI on quay is created and `meta.yaml` points to the correct docker image.  Can we close this?

**Comment by ibuziuk** [comment]
yes, closing
