### ISSUE TITLE
Sprint #135

### ISSUE THREAD

**Issue by ibuziuk** [redhat-developer/rh-che#197]
[Working hours budget spreadsheet](https://docs.google.com/spreadsheets/d/1_YsNaGRHID0QNPdSOJYk6tmlBux1kZK_YN8eCCIpzmY/edit#gid=1409688417)

#### Not assigned yet (go ahead and serve yourself 😃)

- [ ] [Cannot start Bayesian analytics LS agent with `Centos NodeJS` stack](https://github.com/redhat-developer/rh-che/issues/189) **estimation**: 20
- [ ] [Cannot start Json LS agent on rh-che stacks](https://github.com/redhat-developer/rh-che/issues/188) **estimation**: 15
- [ ] [Inconsistencies between stacks](https://github.com/redhat-developer/rh-che/issues/147) **estimation**: 20
- [ ] [Remove the need for rhche Docker images](https://github.com/redhat-developer/rh-che/issues/155) **estimation**: 25
- [ ] [Simplify rhche developer onboarding and daily workflow (after openshift-connector is merged to master)](https://github.com/redhat-developer/rh-che/issues/143) **estimation**: 25
- [ ] [Add OpenShift.io logo in Red Hat distribution](https://github.com/redhat-developer/rh-che/issues/123) **estimation**: 15
- [ ] [Provide a nexus repo for rh-che developers/contributors Provide a nexus repo for rh-che developers/contributors](https://github.com/redhat-developer/rh-che/issues/161) **estimation**: 10
- [ ] [Various bugs have been found in 'OpenShiftConnector' while fixing "Error while pumping stream" issue](https://github.com/redhat-developer/rh-che/issues/198) **estimation**: 25
- [ ] [Integrate jdt.ls into Che](https://github.com/eclipse/che/issues/5730) **estimation**: 25

#### Assigned (and usually WIP)
- [ ] [Need to move OutputCustomizers to the according plugins and make them to be loaded according to workspace's settings](https://github.com/eclipse/che/issues/5652) **estimation**:  35
- [ ] [Support for Executing LSP WorkspaceEdit](https://github.com/eclipse/che/issues/5485) - **estimation**: 25
- [ ] [Add Kubernetes LS](https://github.com/redhat-developer/rh-che/issues/213) **estimation**: 70

#### Done (available on OSIO)

- [x] [Inject user KC token in bayesian LS](https://github.com/redhat-developer/rh-che/issues/141) **estimation**: 35
- [x] [Improve idling implementation](https://github.com/redhat-developer/rh-che/issues/154) **estimation**: 5
- [x] [Bad naming of preview URL in Vert.x stack](https://github.com/redhat-developer/rh-che/issues/92) **estimation**: 15
- [x] [Need to increase request timeout between ui and core to make it work with idled che server](https://github.com/fabric8-ui/fabric8-ui/issues/1745) **estimation**:  1
- [x] [Che: Run Command for Vertx (compile vertx:run)](https://github.com/redhat-developer/rh-che/issues/95) **estimation**: 5
- [x] [Che server logs should be written in a PV](https://github.com/redhat-developer/rh-che/issues/212) **estimation**: 25
- [x] [Che: Import context-assist offering an invalid import](https://github.com/redhat-developer/rh-che/issues/103) **estimation**: 5
- [x] [Update "removeContainer" PR so that it would be mergeable to che master branch](https://github.com/redhat-developer/rh-che/issues/175) **estimation**: 5
- [x] [Verify that on master branch Unit Tests are started in their own process now (c.f. CHE-214)](https://github.com/redhat-developer/rh-che/issues/153) **estimation**: 5
- [x] [Rebasing `openshift-connector-wip` issues](https://github.com/redhat-developer/rh-che/issues/200) **estimation**: 20
- [x] [Update to use the Async CheStarter API from Codebases](https://github.com/fabric8-services/fabric8-wit/issues/1506) **estimation**:  25

### Code Review

- [ ] [Add option to start workspaces on a different namespace](https://github.com/redhat-developer/rh-che/issues/131) **estimation**: 35

### Metrics

|  | Planned | Result |
| --- | --: | --: |
| **Budget** |  |  |
## Sprint Queries

**Enterprise Team**:
[`issues: all`](https://github.com/issues?utf8=%E2%9C%93&q=label%3Asprint%2Fcurrent-sprint+label%3Ateam%2Fenterprise+repo%3Aeclipse%2Fche+repo%3Acodenvy%2Fcodenvy+repo%3Acodenvy%2Fartik-enterprise+repo%3Acodenvy%2Fplanning+repo%3Acodenvy%2Fcustomer-saas), [`issues: open`](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aopen+label%3Asprint%2Fcurrent-sprint+label%3Ateam%2Fenterprise+repo%3Aeclipse%2Fche+repo%3Acodenvy%2Fcodenvy+repo%3Acodenvy%2Fartik-enterprise+repo%3Acodenvy%2Fplanning+repo%3Acodenvy%2Fcustomer-saas+), [`issues: closed`](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aclosed+label%3Asprint%2Fcurrent-sprint+label%3Ateam%2Fenterprise+repo%3Aeclipse%2Fche+repo%3Acodenvy%2Fcodenvy+repo%3Acodenvy%2Fartik-enterprise+repo%3Acodenvy%2Fplanning+repo%3Acodenvy%2Fcustomer-saas+), [`issues: no status`](https://github.com/issues?utf8=%E2%9C%93&q=label%3Asprint%2Fcurrent-sprint+label%3Ateam%2Fenterprise+-label%3Astatus%2Fanalyzing+-label%3Astatus%2Fblocked+-label%3Astatus%2Fcode-review+-label%3Astatus%2Fin-progress+-label%3Astatus%2Finfo-needed+-label%3Astatus%2Fin-progress+-label%3Astatus%2Fwork-in-progress+-label%3Astatus%2Fopen-for-dev+-label%3Astatus%2Fpending-merge+repo%3Aeclipse%2Fche+repo%3Acodenvy%2Fcodenvy+repo%3Acodenvy%2Fartik-enterprise+repo%3Acodenvy%2Fplanning+repo%3Acodenvy%2Fcustomer-saas+),[`issues: pre-dev`](https://github.com/issues?utf8=%E2%9C%93&q=label%3Asprint%2Fcurrent-sprint+label%3Ateam%2Fenterprise+-label%3Astatus%2Fopen-for-dev+-label%3Astatus%2Fin-progress+-label%3Astatus%2Fcode-review+-label%3Astatus%2Fpending-merge+-label%3Astatus%2Fblocked+-label%3Astatus%2Fwork-in-progress+-label%3Astatus%2Fmerge-ready+repo%3Aeclipse%2Fche+repo%3Acodenvy%2Fcodenvy+repo%3Acodenvy%2Fartik-enterprise+repo%3Acodenvy%2Fplanning+repo%3Acodenvy%2Fcustomer-saas+),[`issues: dev`](https://github.com/issues?utf8=%E2%9C%93&q=label%3Asprint%2Fcurrent-sprint+label%3Ateam%2Fenterprise+-label%3Astatus%2Finfo-needed+-label%3Astatus%2Fanalyzing+-label%3Astatus%2Fopen-for-dev+-label%3Astatus%2Fpending-merge+-label%3Astatus%2Fblocked+-label%3Astatus%2Fwork-in-progress+repo%3Aeclipse%2Fche+repo%3Acodenvy%2Fcodenvy+repo%3Acodenvy%2Fartik-enterprise+repo%3Acodenvy%2Fplanning+repo%3Acodenvy%2Fcustomer-saas+),[`issues: pending merge`](https://github.com/issues?utf8=%E2%9C%93&q=label%3Asprint%2Fcurrent-sprint+label%3Ateam%2Fenterprise+-label%3Astatus%2Finfo-needed+-label%3Astatus%2Fanalyzing+-label%3Astatus%2Fopen-for-dev+-label%3Astatus%2Fin-progress+-label%3Astatus%2Fcode-review+-label%3Astatus%2Fblocked+-label%3Astatus%2Fwork-in-progress+repo%3Aeclipse%2Fche+repo%3Acodenvy%2Fcodenvy+repo%3Acodenvy%2Fartik-enterprise+repo%3Acodenvy%2Fplanning+repo%3Acodenvy%2Fcustomer-saas+)

[`bugs: blocker`](https://github.com/issues?utf8=%E2%9C%93&q=label%3Asprint%2Fcurrent-sprint+label%3Ateam%2Fenterprise+label%3Akind%2Fbug+label%3Aseverity%2Fblocker+repo%3Aeclipse%2Fche+repo%3Acodenvy%2Fcodenvy+repo%3Acodenvy%2Fartik-enterprise+repo%3Acodenvy%2Fplanning+repo%3Acodenvy%2Fcustomer-saas+),[`issues: blocked`](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aopen+label%3Asprint%2Fcurrent-sprint+label%3Ateam%2Fenterprise+label%3Astatus%2Fblocked+repo%3Aeclipse%2Fche+repo%3Acodenvy%2Fcodenvy+repo%3Acodenvy%2Fartik-enterprise+repo%3Acodenvy%2Fplanning+repo%3Acodenvy%2Fcustomer-saas+)

[`PRs: all`](https://github.com/issues?utf8=%E2%9C%93&q=is%3Apr+label%3Asprint%2Fcurrent-sprint+label%3Ateam%2Fenterprise+repo%3Aeclipse%2Fche+repo%3Acodenvy%2Fcodenvy+repo%3Acodenvy%2Fartik-enterprise+repo%3Acodenvy%2Fplanning+repo%3Acodenvy%2Fcustomer-saas+), [`PRs: open`](https://github.com/issues?utf8=%E2%9C%93&q=is%3Apr+is%3Aopen+label%3Asprint%2Fcurrent-sprint+label%3Ateam%2Fenterprise+repo%3Aeclipse%2Fche+repo%3Acodenvy%2Fcodenvy+repo%3Acodenvy%2Fartik-enterprise+repo%3Acodenvy%2Fplanning+repo%3Acodenvy%2Fcustomer-saas+), [`PRs: closed`](https://github.com/issues?utf8=%E2%9C%93&q=is%3Apr+is%3Aclosed+label%3Asprint%2Fcurrent-sprint+label%3Ateam%2Fenterprise+repo%3Aeclipse%2Fche+repo%3Acodenvy%2Fcodenvy+repo%3Acodenvy%2Fartik-enterprise+repo%3Acodenvy%2Fplanning+repo%3Acodenvy%2Fcustomer-saas+)

**Previous Sprint**: https://github.com/redhat-developer/rh-che/issues/138
