### ISSUE TITLE
Sprint #136

### ISSUE THREAD

**Issue by l0rd** [redhat-developer/rh-che#251]
[Working hours budget spreadsheet](https://docs.google.com/spreadsheets/d/1_YsNaGRHID0QNPdSOJYk6tmlBux1kZK_YN8eCCIpzmY/edit#gid=1959589069)

### Issues tied to objectives
- [ ] [Implement Github token provider that retrieves token from keycloak](https://github.com/redhat-developer/rh-che/issues/108) **estimation**: 25
- [ ] [Placeholders for Content Assist](https://github.com/redhat-developer/rh-che/issues/257) **estimation**: 15
- [x] [Add debug commands for Vert.x and Spring Boot projects generated from OpenShift.io](https://github.com/redhat-developer/rh-che/issues/238) **estimation**: 5
- [ ] [Debugger fails if not on incognito mode](https://github.com/redhat-developer/rh-che/issues/233) **estimation**: 1
- [ ] [Push to registry.devshift.net only if verification passes](https://github.com/redhat-developer/rh-che/issues/80) **estimation**: 5
- [ ] [Inconsistencies between stacks](https://github.com/redhat-developer/rh-che/issues/147) **estimation**: 20
- [x] ["Git" menu items are disabled after workspace creation and only after a while become available](https://github.com/redhat-developer/rh-che/issues/230) **estimation**: 2
- [ ] [Population of workspace github preferences using Keycloak & GitHub API](https://github.com/redhat-developer/rh-che/issues/231) **estimation**: 20
- [ ] [Move single workspace enforcement to che server](https://github.com/redhat-developer/rh-che/issues/226) **estimation**: 25

#### Assigned (and usually WIP)
- [ ] [Add option to start workspaces on a different namespace](https://github.com/redhat-developer/rh-che/issues/131) **estimation**: 10
- [x] [Add OpenShift.io logo in Red Hat distribution](https://github.com/redhat-developer/rh-che/issues/123) **estimation**: 15
- [x] [Che projects do not have maven nature in OSIO (spring-boot / vertx stacks)](https://github.com/redhat-developer/rh-che/issues/228) **estimation**: 1
- [ ] [Hot deployment does not work on osio for vert.x / spring-boot projects when started via "run" / "debug" commands](https://github.com/redhat-developer/rh-che/issues/254) **estimation**: 3
- [ ] [SPI OpenShift Infrastructure: support recipes of type dockerimage](https://github.com/redhat-developer/rh-che/issues/250)  **estimation**: 70 (Ilya / Angel)
- [ ] [Run che-multiuser branch on OpenShift](https://github.com/redhat-developer/rh-che/issues/247) **estimation**: 30
- [ ] [Simplify rhche developer onboarding and daily workflow (after openshift-connector is merged to master)](https://github.com/redhat-developer/rh-che/issues/143) **estimation**: 25
- [ ] [Simplify rh-che build: remove upstream build and align to Che upstream release](https://github.com/redhat-developer/rh-che/issues/249) **estimation**: part of epic^ estimation
- [ ] [Integrate jdt.ls into Che](https://github.com/redhat-developer/rh-che/issues/211)  **estimation**: 25
- [ ] [Need to move OutputCustomizers to the according plugins and make them to be loaded according to workspace's settings](https://github.com/redhat-developer/rh-che/issues/207) **estimation**: 35
- [ ] [Add Kubernetes LS](https://github.com/redhat-developer/rh-che/issues/213)  **estimation**: 70

### Code Review
- [ ] [Support for Executing LSP WorkspaceEdit](https://github.com/redhat-developer/rh-che/issues/210) **estimation**: 5

### Metrics

|  | Planned | Result |
| --- | --: | --: |
| **Budget** |  |  |
## Sprint Queries

**Enterprise Team**:
[`issues: all`](https://github.com/issues?utf8=%E2%9C%93&q=label%3Asprint%2Fcurrent-sprint+label%3Ateam%2Fenterprise+repo%3Aeclipse%2Fche+repo%3Acodenvy%2Fcodenvy+repo%3Acodenvy%2Fartik-enterprise+repo%3Acodenvy%2Fplanning+repo%3Acodenvy%2Fcustomer-saas), [`issues: open`](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aopen+label%3Asprint%2Fcurrent-sprint+label%3Ateam%2Fenterprise+repo%3Aeclipse%2Fche+repo%3Acodenvy%2Fcodenvy+repo%3Acodenvy%2Fartik-enterprise+repo%3Acodenvy%2Fplanning+repo%3Acodenvy%2Fcustomer-saas+), [`issues: closed`](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aclosed+label%3Asprint%2Fcurrent-sprint+label%3Ateam%2Fenterprise+repo%3Aeclipse%2Fche+repo%3Acodenvy%2Fcodenvy+repo%3Acodenvy%2Fartik-enterprise+repo%3Acodenvy%2Fplanning+repo%3Acodenvy%2Fcustomer-saas+), [`issues: no status`](https://github.com/issues?utf8=%E2%9C%93&q=label%3Asprint%2Fcurrent-sprint+label%3Ateam%2Fenterprise+-label%3Astatus%2Fanalyzing+-label%3Astatus%2Fblocked+-label%3Astatus%2Fcode-review+-label%3Astatus%2Fin-progress+-label%3Astatus%2Finfo-needed+-label%3Astatus%2Fin-progress+-label%3Astatus%2Fwork-in-progress+-label%3Astatus%2Fopen-for-dev+-label%3Astatus%2Fpending-merge+repo%3Aeclipse%2Fche+repo%3Acodenvy%2Fcodenvy+repo%3Acodenvy%2Fartik-enterprise+repo%3Acodenvy%2Fplanning+repo%3Acodenvy%2Fcustomer-saas+),[`issues: pre-dev`](https://github.com/issues?utf8=%E2%9C%93&q=label%3Asprint%2Fcurrent-sprint+label%3Ateam%2Fenterprise+-label%3Astatus%2Fopen-for-dev+-label%3Astatus%2Fin-progress+-label%3Astatus%2Fcode-review+-label%3Astatus%2Fpending-merge+-label%3Astatus%2Fblocked+-label%3Astatus%2Fwork-in-progress+-label%3Astatus%2Fmerge-ready+repo%3Aeclipse%2Fche+repo%3Acodenvy%2Fcodenvy+repo%3Acodenvy%2Fartik-enterprise+repo%3Acodenvy%2Fplanning+repo%3Acodenvy%2Fcustomer-saas+),[`issues: dev`](https://github.com/issues?utf8=%E2%9C%93&q=label%3Asprint%2Fcurrent-sprint+label%3Ateam%2Fenterprise+-label%3Astatus%2Finfo-needed+-label%3Astatus%2Fanalyzing+-label%3Astatus%2Fopen-for-dev+-label%3Astatus%2Fpending-merge+-label%3Astatus%2Fblocked+-label%3Astatus%2Fwork-in-progress+repo%3Aeclipse%2Fche+repo%3Acodenvy%2Fcodenvy+repo%3Acodenvy%2Fartik-enterprise+repo%3Acodenvy%2Fplanning+repo%3Acodenvy%2Fcustomer-saas+),[`issues: pending merge`](https://github.com/issues?utf8=%E2%9C%93&q=label%3Asprint%2Fcurrent-sprint+label%3Ateam%2Fenterprise+-label%3Astatus%2Finfo-needed+-label%3Astatus%2Fanalyzing+-label%3Astatus%2Fopen-for-dev+-label%3Astatus%2Fin-progress+-label%3Astatus%2Fcode-review+-label%3Astatus%2Fblocked+-label%3Astatus%2Fwork-in-progress+repo%3Aeclipse%2Fche+repo%3Acodenvy%2Fcodenvy+repo%3Acodenvy%2Fartik-enterprise+repo%3Acodenvy%2Fplanning+repo%3Acodenvy%2Fcustomer-saas+)

[`bugs: blocker`](https://github.com/issues?utf8=%E2%9C%93&q=label%3Asprint%2Fcurrent-sprint+label%3Ateam%2Fenterprise+label%3Akind%2Fbug+label%3Aseverity%2Fblocker+repo%3Aeclipse%2Fche+repo%3Acodenvy%2Fcodenvy+repo%3Acodenvy%2Fartik-enterprise+repo%3Acodenvy%2Fplanning+repo%3Acodenvy%2Fcustomer-saas+),[`issues: blocked`](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aopen+label%3Asprint%2Fcurrent-sprint+label%3Ateam%2Fenterprise+label%3Astatus%2Fblocked+repo%3Aeclipse%2Fche+repo%3Acodenvy%2Fcodenvy+repo%3Acodenvy%2Fartik-enterprise+repo%3Acodenvy%2Fplanning+repo%3Acodenvy%2Fcustomer-saas+)

[`PRs: all`](https://github.com/issues?utf8=%E2%9C%93&q=is%3Apr+label%3Asprint%2Fcurrent-sprint+label%3Ateam%2Fenterprise+repo%3Aeclipse%2Fche+repo%3Acodenvy%2Fcodenvy+repo%3Acodenvy%2Fartik-enterprise+repo%3Acodenvy%2Fplanning+repo%3Acodenvy%2Fcustomer-saas+), [`PRs: open`](https://github.com/issues?utf8=%E2%9C%93&q=is%3Apr+is%3Aopen+label%3Asprint%2Fcurrent-sprint+label%3Ateam%2Fenterprise+repo%3Aeclipse%2Fche+repo%3Acodenvy%2Fcodenvy+repo%3Acodenvy%2Fartik-enterprise+repo%3Acodenvy%2Fplanning+repo%3Acodenvy%2Fcustomer-saas+), [`PRs: closed`](https://github.com/issues?utf8=%E2%9C%93&q=is%3Apr+is%3Aclosed+label%3Asprint%2Fcurrent-sprint+label%3Ateam%2Fenterprise+repo%3Aeclipse%2Fche+repo%3Acodenvy%2Fcodenvy+repo%3Acodenvy%2Fartik-enterprise+repo%3Acodenvy%2Fplanning+repo%3Acodenvy%2Fcustomer-saas+)

**Previous Sprint**: https://github.com/redhat-developer/rh-che/issues/138

**Comment by skabashnyuk** [comment]
Any activity around https://github.com/redhat-developer/rh-che/issues/107 in this sprint?

**Comment by ibuziuk** [comment]
@skabashnyuk we definitely will not be able to deliver everything from multi-tenant epic in the next sprint, but we could take a few items. Any preferences?

**Comment by skabashnyuk** [comment]
Don't know. I thought I've heard that @davidfestal is going to do something around https://github.com/redhat-developer/rh-che/issues/107 aka Multiuser che in next sprint. Curious what was it? @davidfestal  can you clarify?

**Comment by davidfestal** [comment]
@skabashnyuk I'm currently finishing a POC to attempt simplifying the Keycloak integration according to @alexeykazakov guidelines. But this week I'm going to work on #247 which is certainly an important step to the multi-tenacy support in OSIO.
