### ISSUE TITLE
Port to multi-tenant branch missing commits from rh-che master branch

### ISSUE THREAD

**Issue by l0rd** [redhat-developer/rh-che#440]
An example was #433 but there must be other stuff that hasn't been synch with multi-tenant branch.

**Comment by ibuziuk** [comment]
Commit diff between `multi-tenant-rh-che` and `master`

> * d8655d6 - (origin/master, origin/HEAD, master) Bump to version 5.21.0 (11 days ago)
> * 071cdda - Bump to version 5.20.1 (3 weeks ago)
> * 8beb12e - Update to the docker build script (3 weeks ago)
> * 1c334f4 - Sync rh-che with upstream che v5.20 (3 weeks ago)
> * 961798b - Enable functional tests on pull requests. (3 weeks ago)
> * e470151 - Install git and do checkout after that. (4 weeks ago)
> * 4f0549f - Add check to cico_build.sh if current build is from pull request. (4 weeks ago)
> * 398d911 - Changed nodejs6 to nodejs-centos (4 weeks ago)
> * cbcf46b - Removed scl enable rh-nodejs6 dependency in node stack (4 weeks ago)
> * 7bab41c - Update to che v5.18.1 (5 weeks ago)
> * 4e7de79 - (ibuziuk/master, 5.18.1) Revert "openshift.io #1238: Adding keycloak token validation to the '/user' endpoint" (5 weeks ago)
> * 6fdd55a - openshift.io #1238: Adding keycloak token validation to the '/user' endpoint (5 weeks ago)
> * e882a92 - openshift.io #1215: Fixing typo in stacks.json (6 weeks ago)
> * 4c9cf65 - Fix missing comma in stacks.json (6 weeks ago)
> * 9008bbb - Add CentOS .NET 2.0 Stack (6 weeks ago)
> * 0c5380e - Sync stacks.json with upstream version (6 weeks ago)
> * 04230c8 - Fixing local_docker_create_images_and_tag.sh script with right location of cico scripts (6 weeks ago)
> * bfad140 - rh-che #379: Adding missing 'com.fasterxml.jackson.core' dependency (7 weeks ago)
> * 4a87a36 - rh-che #379:  Migrating to a new GitHub token endpoint, but also supporting an old one

**Comment by ibuziuk** [comment]
4 Commits related to updates in `keycloak-plugin-token-provider` are not relevant since this plugin does not exist in `multi-tenant-rh-che` branch:
- [ ] 4e7de79 - (ibuziuk/master, 5.18.1) Revert "openshift.io #1238: Adding keycloak token validation to the '/user' endpoint" (5 weeks ago)
- [ ] 6fdd55a - openshift.io #1238: Adding keycloak token validation to the '/user' endpoint (5 weeks ago)
- [ ] bfad140 - rh-che #379: Adding missing 'com.fasterxml.jackson.core' dependency (7 weeks ago)
- [ ] 4a87a36 - rh-che #379:  Migrating to a new GitHub token endpoint, but also supporting an old one (7 weeks ago)

**Comment by ibuziuk** [comment]
Commits with bumping upstream version are also not relevant both `master` and `multi-tenant-rh-che` now using `5.21.0` upstream version of che:
- [ ] 7bab41c - Update to che v5.18.1 (5 weeks ago)
- [ ] 1c334f4 - Sync rh-che with upstream che v5.20 (3 weeks ago)
- [ ] d8655d6 - (origin/master, origin/HEAD, master) Bump to version 5.21.0 (11 days ago)
- [ ] 071cdda - Bump to version 5.20.1 (3 weeks ago)

**Comment by ibuziuk** [comment]
`stacks.json` related commits are not relevant since currently those are identical between `master` and `multi-tenant-rh-che`:

- [ ] e882a92 - openshift.io #1215: Fixing typo in stacks.json (6 weeks ago)
- [ ] 4c9cf65 - Fix missing comma in stacks.json (6 weeks ago)
- [ ] 9008bbb - Add CentOS .NET 2.0 Stack (6 weeks ago)
- [ ] 0c5380e - Sync stacks.json with upstream version (6 weeks ago)
- [ ]  398d911 - Changed nodejs6 to nodejs-centos (4 weeks ago)
- [ ] cbcf46b - Removed scl enable rh-nodejs6 dependency in node stack (4 weeks ago)

**Comment by ibuziuk** [comment]
@rhopp do we need to port this `.ci` related changes required for functional tests to `multi-tenant-rh-che` ? 

- [ ] 961798b - Enable functional tests on pull requests. (3 weeks ago)
- [ ] e470151 - Install git and do checkout after that. (4 weeks ago)
- [ ] 4f0549f - Add check to cico_build.sh if current build is from pull request. (4 weeks ago)

**Comment by ibuziuk** [comment]
PR https://github.com/redhat-developer/rh-che/pull/469  for:

- [ ] 04230c8 - Fixing local_docker_create_images_and_tag.sh script with right location of cico scripts (6 weeks ago)

**Comment by ibuziuk** [comment]
No need to port:
- [ ] 8beb12e - Update to the docker build script (3 weeks ago)
`cico_do_docker_build_tag_push.sh` are identical in two branches

**Comment by ibuziuk** [comment]
Multi-tenant template has been also updated https://github.com/redhat-developer/rh-che/pull/474
with JVM flags improvements for che-server https://github.com/fabric8-services/fabric8-tenant-che/commit/eccec4c622d174ceb5600b247021d08a0fb57a83

**Comment by ibuziuk** [comment]
@l0rd I think we can close this issue now

**Comment by l0rd** [comment]
thanks @ibuziuk
