### ISSUE TITLE
Deploy Che6 on OSIO

### ISSUE THREAD

**Issue by l0rd** [redhat-developer/rh-che#448]
- [x] Build rh-che on top of che6 https://github.com/redhat-developer/rh-che/pull/461
- [x] Workspace idling and stop using users' tokens https://github.com/redhat-developer/rh-che/issues/501
- [x] Update che starter to support Che v6 API #515 
- [x] Add ability to configure logs dirs for agents https://github.com/eclipse/che/issues/7807
- [x] Port "Use one OkHttpClient for Che server" to Che v6 #516
- [x] Port "Introduce wsagent ping success threshold" to master #500 
- [ ] Implement a migration script for workspaces source files #477
