### ISSUE TITLE
Cleanup instructions and yaml files in different repositories

### ISSUE THREAD

**Issue by l0rd** [redhat-developer/rh-che#452]
Related to https://github.com/eclipse/che/issues/7318

- [ ] Replace [yaml](https://github.com/eclipse/che/blob/che6/dockerfiles/init/modules/openshift/files/scripts/che-openshift.yml) with a template in eclipse/che (like the one in [rh-che](https://github.com/redhat-developer/rh-che/blob/multi-tenant-rh-che/openshift/rh-che.app.yaml#L320:10))
- [ ] Update upstream instruction to deploy Che: 
   - [ ] Use a template for OCP
   - [ ] Use minishift addon for minishift

N.B. This work should be done for Che 6 (c.f. issue https://github.com/eclipse/che/issues/7321)

**Comment by ibuziuk** [comment]
Closing as outdated
