### ISSUE TITLE
Activities related to Che6 deployment

### ISSUE THREAD

**Issue by l0rd** [redhat-developer/rh-che#483]
This is about some of the activities that are described in the upstream epic https://github.com/eclipse/che/issues/7321. In particular:

- [x] Che Deployment on OpenShift should be as easy as on Docker - [#6097](https://github.com/eclipse/che/issues/6097)
  - [x] Verify and eventually fix all the Che runtime stacks on minishift - cf #155 
- [ ] Che 6 OpenShift template - [#7318](https://github.com/eclipse/che/issues/7318) and #452
- [ ] Che 6 MiniShift add-on: make sure that the addon works with Che 6 
- [ ] Docs: Deploy with OpenShift template / MiniShift add-on
