### ISSUE TITLE
Creating a first minimal viable feature of pair programming with Che-Atom teletype

### ISSUE THREAD

**Issue by sunix** [redhat-developer/rh-che#517]
MVF to join an existing Atom Teletype portal from Che (as a guest portal).
Final result should end up with a PR in Che6.

- [x] spike https://github.com/redhat-developer/rh-che/issues/438
- [ ] remove hard coded value, set values from Preferences panel (20)
- [ ] package teletype-client for browser (20)
- [ ] clean up, concider using jsinterop instead of overlays (25)
- [ ] create a new project type "remote teletype project", shown in project explorer (50)
- [ ] simplify login flow, user shouldn't go through https://teletype.atom.io/login (30)

**Comment by slemeur** [comment]
Linking to https://github.com/eclipse/che/issues/8286

**Comment by garagatyi** [comment]
Since this issue is for other teams I believe that we can close it in our repo. Feel free to reopen if you think otherwise.
