### ISSUE TITLE
Stacks for OSIO on RHEL

### ISSUE THREAD

**Issue by slemeur** [redhat-developer/rh-che#519]
## Goals
All prod and user facing images must be on a Red Hat OS, RHEL is preferred as default and RHEL must be available as an option.

## Linked issues and Subtasks
- [ ] [Create a new Che Dockerfile.rhel](https://github.com/eclipse/che/tree/master/dockerfiles/che) that is based on RHEL #611 
- [ ] Create a [Che runtime base stack](https://github.com/eclipse/che-dockerfiles/tree/master/recipes/stack-base) based on RHEL
- [ ] [Che runtime stacks for OSIO](https://github.com/redhat-developer/che-dockerfiles/) should be based on RHEL  
- [ ] CI scripts (to build Che) should run on RHEL

**Comment by ibuziuk** [comment]
@slemeur this looks like deprecated now due to Che 7 and UBI. WDYT about closing this one?
