### ISSUE TITLE
Add che-migration-service app to dsaas

### ISSUE THREAD

**Issue by l0rd** [redhat-developer/rh-che#574]
- [x] Che-starter
    - [x] Adding toggle for Che6 and handle the migration-service call (Ilya - `5` working hours)
- [x] Che migration service
    - [x] Make an asynchronous call to migration-service (David)  (Ilya - `5` working hours)
- [x] Che migration service
    - [x] ~~Use the Che secret to ask fabric8-auth the Che token~~ Use user KC token to call Che API and OSO Proxy (David)
    - [x] Create the new dsaas service (service yaml, adapt the CI, ~~create an issue for CM creation~~) (David)
- [x] Work with SD team for a massive update script (Ilya - `5` working hours) related housekeeping issue https://gitlab.cee.redhat.com/dtsd/housekeeping/issues/1577

**Comment by ibuziuk** [comment]
FYI. `migrate.to.che6` toggle have been added to prod / prod-preview with `userWithId` strategy

**Comment by davidfestal** [comment]
Migration service is ready on dsaas production. it seems only the work with SD team about massive migration script is remaining to close this issue.

**Comment by ibuziuk** [comment]
https://gitlab.cee.redhat.com/dtsd/housekeeping/issues/1577 is closed so Closing this one
