### ISSUE TITLE
Remove dashboard features that are not supposed to work on OSIO

### ISSUE THREAD

**Issue by l0rd** [redhat-developer/rh-che#608]
Some features like custom dockerfile based stack just don't work on OSIO so these should be not enabled on Che dashboard on OSIO:

- [x] compose recipe is not supported on openshift.io  [#779](https://github.com/redhat-developer/rh-che/issues/779)
- [x] Custom Dockerfile based stacks
- [x] Impossible to import from github account from the dashboard #727
- [ ] Unable to remove default machine while creating stack eclipse/che#10488
- [ ] Dev-machine can be removed after renaming eclipse/che#10487
- [x] Section "Machines" disappeared while renaming stack eclipse/che#10486

**Comment by ibuziuk** [comment]
I believe this issue is outdated now. Dashboard functionality is reconsidered as part of the codenvy.io -> openshift.io transition - https://github.com/redhat-developer/rh-che/issues/701

**Comment by ibuziuk** [comment]
after discussing this issue with @l0rd it was decided to add it to the codenvy.io -> openshift.io transition - #701 epic

**Comment by ibuziuk** [comment]
initial task for this issue would be identifying all the parts that are not working. @rhopp  Maybe QA would be able to help with that one and provide a bullet list of all the pieces that are need to be fixed / disabled on che osio dashboard ?

**Comment by rhopp** [comment]
@ibuziuk Definitely. I'll create an issue for that and include it in this sprint. We will also cooperate with upstream Che QA on this.

**Comment by rhopp** [comment]
@ibuziuk Katka gone through the dashboard and identified few issues. Those issues were already identified (as for example https://github.com/redhat-developer/rh-che/issues/727) or there were also present in upstream (and reported there as for example https://github.com/eclipse/che/issues/10488).

We didn't think about stuff which "works" or "does nothing" as for example Orgatinzations page and such (which is already scheduled to be removed as part of https://github.com/redhat-developer/rh-che/issues/707)

Am I right, @Katka92 ?

**Comment by ibuziuk** [comment]
could all the issue that were found as part of the investigation (both rh-che & upstream) be added to the issue description as checkboxes as it was initially planned - https://github.com/redhat-developer/rh-che/issues/608#issuecomment-401882388 ?

**Comment by Katka92** [comment]
Found issues:
- [ ] #727 
- [ ] eclipse/che#10488
- [ ] https://github.com/eclipse/che/issues/10487
- [ ] https://github.com/eclipse/che/issues/10486

I'm affraid, I can't recover more issues there were not created by me but are related with this issue.

**Comment by ibuziuk** [comment]
@Katka92 thanks, could you please add those issues to the description in the format that is currently in place : - [ ] issue title #issue_reference

**Comment by Katka92** [comment]
@ibuziuk updated, hope now it is ok :)

**Comment by ibuziuk** [comment]
great, thank you!

**Comment by ibuziuk** [comment]
Dashboard already does not show compose based stacks since those are not shown for k8s / openshift infrastructure.

**Comment by ibuziuk** [comment]
I believe this issue can be closed. Since 2 remaining issues are just dashboard bugs and does not block codeny.io migration
