### ISSUE TITLE
Finalize and publish a Che APB that allows OpenShift users to install/configure and use Che in their OCP/OSD/OS

### ISSUE THREAD

**Issue by l0rd** [redhat-developer/rh-che#699]
Che apb allows to deploy Eclipse Che into your OpenShift project using an APB. Need to fix the following issues in order to finalize the initial Eclipse Che deployment setup via APB:

- [x]  Che APB installation fails on minishift with default configuration [#19](https://github.com/ansibleplaybookbundle/eclipse-che-apb/issues/19), [#781](https://github.com/redhat-developer/rh-che/issues/781)
- [x] Support external PostgreSQL and Keycloak [#7](https://github.com/ansibleplaybookbundle/eclipse-che-apb/issues/7)
- [ ] Support creating workspace objects in personal namespaces [#16](https://github.com/ansibleplaybookbundle/eclipse-che-apb/issues/16)
- [x] Support TLS [#6](https://github.com/ansibleplaybookbundle/eclipse-che-apb/issues/6)
- [ ] No more than one Che per cluster [#18](https://github.com/ansibleplaybookbundle/eclipse-che-apb/issues/18)
- [ ] Changing ASB configuration should not be a requirement [#17](https://github.com/ansibleplaybookbundle/eclipse-che-apb/issues/17)

[1]  https://github.com/ansibleplaybookbundle/eclipse-che-apb

https://issues.jboss.org/browse/RACHEL-20

**Comment by l0rd** [comment]
There are 2 subtasks for this issue:
- Using RHEL keycloak and postgres
- Building Che stacks from scratch should be part of the APB deployment

**Comment by l0rd** [comment]
@ibuziuk everything looks good, I have added 2 subtasks:
- No more than one Che per cluster [#18](https://github.com/ansibleplaybookbundle/eclipse-che-apb/issues/18)
- Changing ASB configuration should not be a requirement [#17](https://github.com/ansibleplaybookbundle/eclipse-che-apb/issues/17)

**Comment by ibuziuk** [comment]
Closing since che apb is planned to be deprecated in the short run
