### ISSUE TITLE
Transition of Codenvy.io -> OSIO

### ISSUE THREAD

**Issue by nickboldt** [redhat-developer/rh-che#701]
**Issue problem:** 
- [x] Slow mount of PVC for che workspaces - can prevent workspaces from starting. [#4079](https://github.com/openshiftio/openshift.io/issues/4079)
- [x] Unable to start a workspace from a factory url [#839](https://github.com/redhat-developer/rh-che/issues/839)
- [x] Increase memory limit for workspace namespaces to 3Gi [#675](https://github.com/redhat-developer/rh-che/issues/675)
- [x] Che.Openshift.io stacks (**WIP** @eivantsov)
  - [x] Need to manually remove compose based stacks from prod / prod-preview [#843](https://github.com/redhat-developer/rh-che/issues/843)
- [x] Various issues with stacks on OSIO [#763](https://github.com/redhat-developer/rh-che/issues/763)
- [x] Connect your own Docker Registry (protected by username/password) [#680](https://github.com/redhat-developer/rh-che/issues/680) (**DONE**)
- [x] Disable Organizations on che.openshift.io  [#707](https://github.com/redhat-developer/rh-che/issues/707)
- [x] Add limitations for workspace sharing on `che.openshift.io` #798
- [x] Pull Request Workflow [#727](https://github.com/redhat-developer/rh-che/issues/727)
- [x] Convert Factories from Eclipse Che website to point to che.openshift.io [#709](https://github.com/redhat-developer/rh-che/issues/709)
  - [x] Fix migrated factories that don't work fully and push the new list to Eclipse [#729](https://github.com/redhat-developer/rh-che/issues/729)
  - [x] Add tracking of factories in Telemetry [#749](https://github.com/redhat-developer/rh-che/issues/749)
- [x] Remove dashboard features that are not supposed to work on OSIO #608

**Comment by ibuziuk** [comment]
@eivantsov would you be able to add new stacks created as part of this issue (Che.Openshift.io stacks) to rh-che ?

**Comment by eivantsov** [comment]
@ibuziuk should I issue a PR against https://github.com/redhat-developer/rh-che/blob/master/assembly/fabric8-stacks/src/main/resources/stacks.json?

**Comment by ibuziuk** [comment]
@eivantsov sorry for the delay in response - completely missed your last message :/ Yeah, that would be great if we could add all new stacks related to `codenvy.io` migration to rhche. But before we do this I believe we would need to build and push it to `registry.devshift.net` where all che osio specific images are living. @l0rd @riuvshin @eivantsov wdyt about adding all new `codenvy.io` images to https://github.com/redhat-developer/che-dockerfiles  first before updating stacks.json?

**Comment by eivantsov** [comment]
So:

1. Move Dockerfiles to rh repo
2. Test via custom stacks on che.openshift.io
3. Update stacks.json

Does such a plan look ok?

**Comment by ibuziuk** [comment]
@eivantsov sounds like exactly what is required

**Comment by ibuziuk** [comment]
Closing this epic in favor of https://github.com/redhat-developer/rh-che/issues/1490
Current pre-requirement for codenvy.io transition is Che 7 GA running on Hosted Che in a stable manner
