### ISSUE TITLE
workspace next walking skeleton

### ISSUE THREAD

**Issue by l0rd** [redhat-developer/rh-che#731]
Placeholder for https://github.com/eclipse/che/issues/10123 for rh-che work

- [ ] Create new files Structure in registry: add theia editor meta, add a test plugin meta. create test tarball with a test plugin and theia editor files: .theia, plugin.yaml (theia), plugin.yaml (plugin) #792 
- [ ] Download of the plugins and editor meta.yaml from the plugin registry. The URL of the plugin registry should be a wsmaster property. Get new properties from workspace attributes #793 
- [ ] Download and extract the plugins tarballs, process yamls. #794
- [ ] Copy the editor plugins in a PV folder that will be shared with the editor container #795 
- [ ] Integrate che-plugin-registry on OSIO with RhChe to use Walking skeleton #806

**Comment by garagatyi** [comment]
All of these tasks are tracked in upstream. We add corresponding issues here to plan sprints, so we don't need this epic-level issue anymore. Closing it.
