### ISSUE TITLE
Add tracking of factories in Telemetry

### ISSUE THREAD

**Issue by davidfestal** [redhat-developer/rh-che#749]
We should track how workspaces are created from factories. See this issue comment https://github.com/redhat-developer/rh-che/issues/709#issuecomment-404136882

- [x] When a workspaces is started from a factory
- [x] What factory has been started
- [x] When an account is created on OSIO from a user who clicked on a factory.

This seems to be a pre-requisite to finalizing the migration of factories (https://github.com/redhat-developer/rh-che/issues/729).

**Comment by slemeur** [comment]
Thanks @davidfestal !

**Comment by ibuziuk** [comment]
> When an account is created on OSIO from a user who clicked on a factory.

@slemeur @l0rd  I also commented in the original issue that this event is not really che related [1], but rather related to the registration flow - https://github.com/openshiftio/openshift.io/issues/3814 

Which team do you think should be in charge of the processing and adding to woopra registration events ?  

IMO the woopra registration event should not be limited to Che factory usecase but rather track in general, from which page the user was redirected to the registration page (I believe it would be quite easy to do via `document.referrer`[2] on the registration side and super useful from the marketing perspective) 

[1] https://github.com/redhat-developer/rh-che/issues/709#issuecomment-404141100
[2] https://developer.mozilla.org/en-US/docs/Web/API/Document/referrer

**Comment by slemeur** [comment]
> IMO the woopra registration event should not be limited to Che factory usecase but rather track in general, from which page the user was redirected to the registration page (I believe it would be quite easy to do via document.referrer[2] on the registration side and super useful from the marketing perspective)

I agree with you @ibuziuk . 
In fact we are interested by all accounts created from the page here: https://github.com/openshiftio/openshift.io/issues/3814 and should be using the referrer to know if the user was coming from a factory or not.

I can create a dedicated issue for that. I believe Auth team should probably be the appropriate team to handle that. wdyt @alexeykazakov ?

**Comment by ibuziuk** [comment]
cc: @sbose78 since Alexey is on PTO till the end of the month

**Comment by davidfestal** [comment]
Let's summarize what has been done for this issue:

PR https://github.com/redhat-developer/rh-che/pull/760 has added some meaningful properties to Telemetry workspace events, that allow tracking factory and stack usage.
More precisely it provides:
- the *__stack Id__* when the started workspace was initially created from a Dashboard stack,
- the *__factory Id, factory owner and factory name__* when the started workspace was initially created from a factory,
- a *__first start__* boolean property that indicates if this is the first time a workspace is started after its creation
- the *__age__* of a started workspace (last start date - creation date) which is important to track for workspace *creations* from factories
- the *__return delay__* of started workspaces, which is the timeframe during which a workspace has been left unused before being restarted, and can give an insight of how frequently workspaces are restarted. 

The 2 last properties can probably be useful more generally to measure user engagement / on-boarding, for all types of workspaces, not only factories.

Based on these new properties, I created the following reports in the prod-preview `test.openshift.io` Woopra instance:
- Most used factories: https://www.woopra.com/live/project/test.openshift.io/reports/analytics/ujyyyn0bw9
- Most used stacks: https://www.woopra.com/live/project/test.openshift.io/reports/analytics/gdyiqlcmfe
- Che active factories (usage of workspaces **_initially created from factories_**, with the usage duration): https://www.woopra.com/live/project/test.openshift.io/reports/analytics/edoiu9bhmx 
- Starts of workspaces from the factories available on the Eclipse Che website (getting started/cloud page), which reflects _**the number of successful clicks on the Eclipse Che website factory links**_: https://www.woopra.com/live/project/test.openshift.io/reports/analytics/i88avfwwrk
- Coming of _**new Che users**_ (with the part of the that first created a workspace from an Eclipse factory): this tracks the event of _**the first time a user starts a Che workspace**_: https://www.woopra.com/live/project/test.openshift.io/reports/analytics/tpympvub2c

The last report uses a metric that is related to this discussion, since it measures the **_number of users that just started using Che_**, so typically Che user on-boarding:
when a user arrives for the first time inside a running workspace, and it provides the source of the workspace definition: factory or stack.

It seems to me it finally provides a metric equivalent to the 3rd one requested in this issue:

> When an account is created on OSIO from a user who clicked on a factory.

@slemeur do you agree ?

**Comment by slemeur** [comment]
This is perfect. 

Excellent work @davidfestal !

Looking forward to see the transition happening!

**Comment by benoitf** [comment]
AFAIK referrer url is something that we mostly don't have anymore on HTTPS website which is almost everywhere now

**Comment by davidfestal** [comment]
Just a thought about what is **_already available_**  in the Che telemetry support, and the ability to start **_marketing campaigns_** that would be better tracked.

Since **_we can already track from which factory a user started its first workspace_** (=> onboarded to che.openshift.io) (owner and factory name), why not **_use factories as much as we can in upcoming marketing campaigns_** such as twitter, etc .., through a factory link that leads to the workspace with the scenario we want the user to try.

If we dedicate a specific OSIO user (as we did for Eclipse web site factories) for this type of factories (associated to marketing campains), and somehow link the factory name to the campaign name/id, that would allow tracking the number of onboarded users through each campaign very easily. All this with the existing Woopra setup and production Che server.

Of course, to work seemlessly, this would require fixing the OSIO factory flow for new unregistered users, so that they would be correctly brought to the workspace without being stopped by the intermediate  steps of the authentication/provisioning flow.

@slemeur @benoitf @ibuziuk  @lord wdyt ?

**Comment by lord** [comment]
@davidfestal sounds good to me!

**Comment by davidfestal** [comment]
> @davidfestal sounds good to me!

Ah, it seems I confused `0` and `o` :-)

@l0rd wdyt think of the previous comment ?

**Comment by slemeur** [comment]
You are perfectly right, that's excellent and powerful. That's exactly why adding telemetry on the factory is important.

**Comment by ibuziuk** [comment]
@davidfestal @slemeur I guess I can close this one - further work on telemetry is planned to be done as part of https://github.com/redhat-developer/rh-che/issues/765
@sbose78 @alexeykazakov btw, guys have you got  a chance to create a separate issue for adding telemetry for the registration flow - https://github.com/redhat-developer/rh-che/issues/749#issuecomment-405890799?
