### ISSUE TITLE
Switch from 'common' to 'unique' pvc strategy 

### ISSUE THREAD

**Issue by ibuziuk** [redhat-developer/rh-che#865]
- [ ] Limit number of created workspaces to 5
- [ ] Need to add a warning on Codebases UI page if user tries to create more than 5 workspaces 
- [ ] Need to notify users that only 5 workspaces are allowed from now on and extra workspaces would be removed soon
- [ ] Need to remove extra workspaces and leave only 5
- [ ] Need to switch strategy from `common` to `unique` in `rhche` cm [1]
- [ ] Need to perform migration of existing workspaces to use `unique` PVC instead of `common` 

[1] https://github.com/redhat-developer/rh-che/blob/master/openshift/rh-che.config.yaml#L9

**Comment by ibuziuk** [comment]
Closing since switch to `unique` strategy is not planned anymore
