### ISSUE TITLE
Maintenance and Monitoring tooling for che.openshift.io

### ISSUE THREAD

**Issue by l0rd** [redhat-developer/rh-che#949]
**Issue problem:** 

Tooling capabilities:

- [ ] Monitor workspace pods that are running for more than X days [issue](https://gitlab.cee.redhat.com/dtsd/housekeeping/issues/2330)
- [ ] Delete a workspace resources if it has been running for more than X days
- [ ] Setup JVM stats monitoring [issue](https://gitlab.cee.redhat.com/dtsd/housekeeping/issues/2347)
- [ ] Admin access to Che server
- [ ] Leverage sentry capabilities
- [ ] Email notifications [issue](https://gitlab.cee.redhat.com/dtsd/housekeeping/issues/2297)

**Comment by ibuziuk** [comment]
@l0rd wdyt about excluding the following issue from the epic:

- [ ] Delete a workspace resources if it has been running for more than X days [#1977](https://gitlab.cee.redhat.com/dtsd/housekeeping/issues/1977) [#730](https://github.com/redhat-developer/rh-che/issues/730)

Not sure if it is a priority for an L train, since this task would definitely require, not only follow up and coordination with the SD team, but also development effort (support of admin token in `che tenant maintainer`). Also it is still not clear, if it will be possible to restore the user data in case of an accident [1], which is crucial to understand before running `che-tenant-maintainer` periodically.

[1] https://gitlab.cee.redhat.com/dtsd/housekeeping/issues/1977#note_473420

**Comment by fche** [comment]
we're close with the last item: https://github.com/redhat-developer/osd-monitor-poc/issues/45
